directory: /data/music
library: /data/musiclibrary.db

plugins:
- ytimport
- describe
- web

ytimport:
  directory: /data/youtube
  import: true
  likes: false
  max_likes: 3
  set: 'like=1'
  min_length: 60
  max_length: 7200
  split_tracks: true
  group_albums: false
