directory: /data/music
library: /data/musiclibrary.db

plugins:
- ytimport
- web

ytimport:
  directory: /data/youtube
  import: true
  likes: true
  max_likes: 3
  set: 'like=1'
  min_len: 60
  max_len: 7200
  split_albums: true
