directory: /data/music
library: /data/musiclibrary.db

paths:
  default: Albums/%title{$albumartist}/$album%aunique{}/$track $title
  singleton: Singles/%title{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
- ytimport
- chroma
- lastgenre
- fetchart
- edit
- info
- describe
- smartplaylist
- random
- duplicates
- web

ui:
  terminal_width: 160

import:
  write: true
  copy: true
  incremental: true
  quiet: false
  quiet_fallback: asis

clutter:
- cover.jpg

chroma:
  auto: true

ytimport:
  directory: /data/ytimport
  import: true
  likes: false
  max_likes: 3
  set:
    somefancyfield: 1
  min_length: 60
  max_length: 7200
  split_tracks: true
  group_albums: true

smartplaylist:
  relative_to: /data/playlists
  playlist_dir: /data/playlists
  forward_slash: false
  playlists:
  - name: all.m3u
    query: ''
  - name: all-by-genre-album.m3u
    query: 'genre+ albumartist+ year+ album+ track+ artist+ title+'

lastgenre:
  auto: true
  canonical: true
