directory: /data/music
library: /data/musiclibrary.db

plugins:
- ytimport
- chroma
- lastgenre
- edit
- info
- describe
- smartplaylist
- random
- web

import:
  write: true
  copy: true
  incremental: true
  quiet: false

chroma:
  auto: true

ytimport:
  directory: /data/ytimport
  import: true
  likes: false
  max_likes: 3
  set: 'like=1'
  min_length: 60
  max_length: 7200
  split_tracks: true
  group_albums: false

smartplaylist:
  relative_to: /data/playlists
  playlist_dir: /data/playlists
  forward_slash: false
  playlists:
  - name: all.m3u
    query: ''
  - name: all-by-genre-album.m3u
    query: 'genre+ albumartist+ year+ album+ track+ artist+ title+'

lastgenre:
  auto: true
  canonical: true
